import React, { useState, useEffect, useRef, useCallback } from 'react'
import DashboardLayout from '../components/DashboardLayout'
import { useAuth } from '../context/AuthContext'
import { agentAPI, filesAPI } from '../api/client'

function downloadAsPDF(content) {
  const sanitized = content
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/\n/g, '<br/>')

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/>
  <title>Code Review Report</title>
  <style>
    @page{margin:2cm}
    body{font-family:'Segoe UI',Arial,sans-serif;font-size:13px;line-height:1.8;color:#1f2937}
    h1{font-size:20px;color:#7c3aed;border-bottom:2px solid #a855f7;padding-bottom:8px;margin-bottom:16px}
    .meta{font-size:11px;color:#6b7280;margin-bottom:24px}
    .content{white-space:pre-wrap}
    .footer{margin-top:40px;font-size:10px;color:#9ca3af;border-top:1px solid #e5e7eb;padding-top:8px}
  </style></head><body>
  <h1>📋 Code Review Report</h1>
  <div class="meta">Generated on ${new Date().toLocaleString()} · NatWest Automator</div>
  <div class="content">${sanitized}</div>
  <div class="footer">Confidential · NatWest Automator AI Platform</div>
  </body></html>`

  const iframe = document.createElement('iframe')
  iframe.style.cssText = 'position:fixed;top:-9999px;left:-9999px;width:0;height:0;border:none'
  document.body.appendChild(iframe)
  iframe.contentDocument.open()
  iframe.contentDocument.write(html)
  iframe.contentDocument.close()
  setTimeout(() => {
    iframe.contentWindow.focus()
    iframe.contentWindow.print()
    setTimeout(() => document.body.removeChild(iframe), 1000)
  }, 300)
}

export default function CodeReviewPage() {
  const { hasPermission } = useAuth()

  const [outputFiles, setOutputFiles] = useState([])
  const [selectedFile, setSelectedFile] = useState(null)
  const [existingContent, setExistingContent] = useState('')
  const [fetchingFiles, setFetchingFiles] = useState(false)

  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)
  const [error, setError] = useState('')
  const [approved, setApproved] = useState(false)
  const [approvedAt, setApprovedAt] = useState(null)
  const [rejected, setRejected] = useState(false)
  const [rejectedAt, setRejectedAt] = useState(null)
  const resultRef = useRef()

  if (!hasPermission('code_review')) {
    return (
      <DashboardLayout title="Code Review">
        <div style={s.denied}>
          <div style={{ fontSize: '3rem' }}>🔒</div>
          <h3 style={s.deniedTitle}>Access Restricted</h3>
          <p style={s.deniedSub}>Your role does not have permission to access this agent.</p>
        </div>
      </DashboardLayout>
    )
  }

  const fetchOutputFiles = useCallback(async () => {
    setFetchingFiles(true)
    try {
      const data = await filesAPI.listOutput('automation')
      setOutputFiles(data.files || [])
    } catch {
      setOutputFiles([])
    } finally {
      setFetchingFiles(false)
    }
  }, [])

  useEffect(() => {
    fetchOutputFiles()
  }, [fetchOutputFiles])

  const selectExistingFile = async (fname) => {
    setSelectedFile(fname)
    setExistingContent('')
    setResult(null)
    setError('')
    try {
      const text = await filesAPI.readOutput(`automation/${fname}`)
      setExistingContent(text)
    } catch {
      setError('Failed to load automation script file.')
    }
  }

  const handleReview = async () => {
    if (!existingContent.trim()) return
    setLoading(true)
    setError('')
    setResult(null)
    setApproved(false); setApprovedAt(null); setRejected(false); setRejectedAt(null)
    try {
      const data = await agentAPI.run('code_review', existingContent, null, 'ollama')
      setResult(data.result)
      setTimeout(() => resultRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 100)
    } catch (err) {
      setError(err.response?.data?.detail || 'Code review failed. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  /* ── approve / reject ── */
  const handleApprove = () => {
    setApproved(true); setApprovedAt(new Date().toLocaleString())
    filesAPI.saveOutput('code_review', result).catch(() => {})
  }
  const handleReject = () => {
    setRejected(true); setRejectedAt(new Date().toLocaleString())
  }

  return (
    <DashboardLayout title="Code Review">
      <div style={s.page}>

        <div>
          <h2 style={s.pageTitle}>Code Review</h2>
          <p style={s.pageSubtitle}>
            Review test code for quality, maintainability, correctness, and best practices adherence.
          </p>
        </div>

        <div style={s.card}>
          <div style={s.cardBody}>

            <p style={s.sectionTitle}>Automation Script</p>
            <p style={s.hint}>Select an automation script previously generated by the Automation agent.</p>

            {fetchingFiles ? (
              <div style={s.loadingBox}>⟳ Loading automation scripts...</div>
            ) : outputFiles.length === 0 ? (
              <div style={s.emptyBox}>
                <div style={{ fontSize: '1.5rem', marginBottom: '6px' }}>💭</div>
                <p>No automation scripts found.</p>
                <p style={{ fontSize: '0.8rem', color: '#9ca3af' }}>
                  Go to <strong>Automation</strong> page to generate one first.
                </p>
              </div>
            ) : (
              <div style={s.fileList}>
                {outputFiles.map(f => (
                  <div
                    key={f.name}
                    style={{
                      ...s.fileListItem,
                      borderColor: selectedFile === f.name ? '#7c3aed' : '#e5e7eb',
                      background: selectedFile === f.name ? 'rgba(124,58,237,0.05)' : '#fff',
                    }}
                    onClick={() => selectExistingFile(f.name)}
                  >
                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px', flex: 1, minWidth: 0 }}>
                      <span>📄</span>
                      <div style={{ minWidth: 0 }}>
                        <div style={s.fileListItemName}>{f.name}</div>
                        <div style={s.fileListItemMeta}>
                          {(f.size / 1024).toFixed(1)} KB · {new Date(f.modified).toLocaleString()}
                        </div>
                      </div>
                    </div>
                    {selectedFile === f.name && (
                      <span style={s.selectedBadge}>✓ Selected</span>
                    )}
                  </div>
                ))}
              </div>
            )}

            {existingContent && (
              <div style={s.preview}>
                <div style={s.previewHead}>
                  <span style={{ fontWeight: 600, fontSize: '0.78rem', color: '#374151' }}>📋 Script Preview</span>
                  <span style={{ fontSize: '0.74rem', color: '#9ca3af' }}>{existingContent.length.toLocaleString()} chars</span>
                </div>
                <textarea
                  style={s.codeEditor}
                  value={existingContent}
                  onChange={e => setExistingContent(e.target.value)}
                />
              </div>
            )}

            {error && <div style={s.errorBox}>⚠️ {error}</div>}

            <button
              style={{
                ...s.actionBtn,
                opacity: loading || !existingContent.trim() ? 0.55 : 1,
                cursor:  loading || !existingContent.trim() ? 'not-allowed' : 'pointer',
              }}
              onClick={handleReview}
              disabled={loading || !existingContent.trim()}
            >
              {loading
                ? <><span style={s.spin}>⟳</span> Reviewing code...</>
                : '🔍  Review Code'
              }
            </button>
          </div>
        </div>

        {result && (
          <div ref={resultRef} style={{
            ...s.resultCard,
            borderColor: approved ? '#bbf7d0' : rejected ? '#fecaca' : '#d8b4fe',
          }}>
            <div style={{
              ...s.resultHead,
              background: approved ? 'rgba(34,197,94,0.05)' : rejected ? 'rgba(239,68,68,0.05)' : 'rgba(124,58,237,0.04)',
              borderColor: approved ? '#bbf7d0' : rejected ? '#fecaca' : '#ede9fe',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}>
                <span style={{ fontSize: '1rem' }}>{approved ? '✅' : rejected ? '❌' : '✅'}</span>
                <span style={{ ...s.resultTitle, color: approved ? '#166534' : rejected ? '#dc2626' : '#4c1d95' }}>
                  {approved ? 'Code Review — Approved' : rejected ? 'Code Review — Rejected' : 'Code Review Complete'}
                </span>
                {approved && <span style={s.approvedBadge}>✅ Approved · {approvedAt}</span>}
                {rejected && <span style={s.rejectedBadge}>❌ Rejected · {rejectedAt}</span>}
              </div>
              <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                <button style={s.copyBtn} onClick={() => navigator.clipboard.writeText(result)}>📋 Copy</button>
                <button style={s.pdfBtn} onClick={() => downloadAsPDF(result)}>⬇️ Download PDF</button>
                {!approved && !rejected && <button style={s.approveBtn} onClick={handleApprove}>✅ Approve</button>}
                {!approved && !rejected && <button style={s.rejectBtn} onClick={handleReject}>❌ Reject</button>}
              </div>
            </div>
            {rejected && (
              <div style={s.rejectedStrip}>❌ This code review has been rejected. Click Review Code to try again.</div>
            )}
            <pre style={{ ...s.resultText, opacity: rejected ? 0.5 : 1 }}>{result}</pre>
            <div style={{ ...s.resultFoot, background: approved ? '#f0fdf4' : rejected ? '#fef2f2' : '#faf5ff' }}>
              {approved
                ? <span style={{ color: '#16a34a', fontWeight: 600 }}>🔒 Code review approved.</span>
                : rejected
                  ? <span style={{ color: '#dc2626', fontWeight: 600 }}>❌ Code review rejected — click <strong>Review Code</strong> to try again.</span>
                  : <span>💡 Review above. Click <strong>Approve</strong> to lock or <strong>Reject</strong> to discard.</span>
              }
            </div>
          </div>
        )}

      </div>
    </DashboardLayout>
  )
}

const s = {
  page:         { display: 'flex', flexDirection: 'column', gap: '20px' },
  pageTitle:    { fontSize: '1.45rem', fontWeight: 800, color: '#1f2937', marginBottom: '4px' },
  pageSubtitle: { fontSize: '0.85rem', color: '#6b7280' },
  card:         { background: '#fff', borderRadius: '14px', border: '1px solid #e5e7eb', boxShadow: '0 1px 6px rgba(0,0,0,0.05)', overflow: 'hidden' },
  cardBody:     { padding: '22px 24px', display: 'flex', flexDirection: 'column', gap: '14px' },
  sectionTitle: { fontSize: '0.85rem', fontWeight: 600, color: '#374151', marginBottom: '2px' },
  hint:         { fontSize: '0.82rem', color: '#6b7280', marginBottom: '4px' },
  fileList:     { display: 'flex', flexDirection: 'column', gap: '6px', maxHeight: '260px', overflowY: 'auto' },
  fileListItem: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '10px 14px', borderRadius: '8px', border: '1px solid',
    cursor: 'pointer', gap: '10px', transition: 'all 0.15s',
  },
  fileListItemName: {
    fontSize: '0.82rem', fontWeight: 600, color: '#1f2937',
    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
  },
  fileListItemMeta: { fontSize: '0.72rem', color: '#9ca3af', marginTop: '2px' },
  selectedBadge: {
    padding: '2px 8px', borderRadius: '5px', fontSize: '0.72rem', fontWeight: 700,
    background: 'rgba(124,58,237,0.1)', color: '#7c3aed', border: '1px solid rgba(124,58,237,0.2)',
    flexShrink: 0,
  },
  loadingBox: {
    padding: '20px', textAlign: 'center', color: '#7c3aed',
    fontSize: '0.88rem', fontWeight: 600,
  },
  emptyBox: {
    padding: '24px', textAlign: 'center', color: '#6b7280',
    background: '#f9fafb', borderRadius: '8px', fontSize: '0.85rem',
  },
  preview:     { border: '1px solid #e5e7eb', borderRadius: '8px', overflow: 'hidden' },
  previewHead: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '7px 12px', borderBottom: '1px solid #e5e7eb', background: '#f9fafb',
  },
  previewText: {
    padding: '10px 12px', fontSize: '0.78rem', lineHeight: 1.6,
    whiteSpace: 'pre-wrap', wordBreak: 'break-word', color: '#374151',
    maxHeight: '120px', overflowY: 'auto', fontFamily: 'inherit', margin: 0,
  },
  codeEditor: {
    width: '100%', minHeight: '300px', padding: '12px 14px', borderRadius: '8px',
    border: '1px solid #d1d5db', background: '#f8fafc', fontSize: '0.875rem',
    fontFamily: 'monospace', lineHeight: 1.65, color: '#1f2937',
    resize: 'vertical', outline: 'none', boxSizing: 'border-box',
  },
  errorBox: {
    background: 'rgba(239,68,68,0.06)', border: '1px solid rgba(239,68,68,0.2)',
    color: '#dc2626', borderRadius: '8px', padding: '10px 14px', fontSize: '0.875rem',
  },
  actionBtn: {
    padding: '12px 24px', borderRadius: '10px', fontWeight: 700, fontSize: '0.95rem',
    border: 'none', background: 'linear-gradient(135deg, #7c3aed, #a855f7)',
    color: '#fff', display: 'inline-flex', alignItems: 'center', gap: '8px',
    boxShadow: '0 3px 12px rgba(124,58,237,0.28)', transition: 'opacity 0.2s', alignSelf: 'flex-start',
  },
  spin: { display: 'inline-block', animation: 'spin 1s linear infinite', fontSize: '1rem' },
  resultCard: {
    background: '#fff', borderRadius: '14px',
    border: '1.5px solid #d8b4fe', boxShadow: '0 2px 14px rgba(124,58,237,0.09)', overflow: 'hidden',
  },
  resultHead: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '12px 18px', borderBottom: '1px solid #ede9fe',
    background: 'rgba(124,58,237,0.04)', flexWrap: 'wrap', gap: '10px',
  },
  resultTitle: { fontSize: '0.9rem', fontWeight: 700, color: '#4c1d95' },
  copyBtn: {
    padding: '6px 14px', borderRadius: '7px', fontSize: '0.8rem', fontWeight: 600,
    background: 'rgba(124,58,237,0.08)', border: '1px solid rgba(124,58,237,0.2)',
    color: '#7c3aed', cursor: 'pointer',
  },
  pdfBtn: {
    padding: '6px 16px', borderRadius: '7px', fontSize: '0.8rem', fontWeight: 700,
    background: 'linear-gradient(135deg, #7c3aed, #a855f7)', border: 'none',
    color: '#fff', cursor: 'pointer', boxShadow: '0 2px 8px rgba(124,58,237,0.22)',
  },
  resultText: {
    padding: '18px 20px', fontSize: '0.875rem', lineHeight: 1.8,
    whiteSpace: 'pre-wrap', wordBreak: 'break-word', color: '#1f2937',
    fontFamily: 'inherit', maxHeight: '500px', overflowY: 'auto', margin: 0,
  },
  resultFoot: {
    padding: '9px 18px', borderTop: '1px solid #f3f4f6',
    background: '#faf5ff', fontSize: '0.75rem', color: '#7c3aed',
  },
  denied:      { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '60vh', textAlign: 'center', gap: '10px' },
  deniedTitle: { fontSize: '1.3rem', fontWeight: 700, color: '#4c1d95' },
  deniedSub:   { color: '#6b7280', fontSize: '0.9rem', maxWidth: '340px' },

  approveBtn: {
    padding: '6px 18px', borderRadius: '7px', fontSize: '0.8rem', fontWeight: 700,
    background: 'linear-gradient(135deg, #16a34a, #22c55e)', border: 'none',
    color: '#fff', cursor: 'pointer', boxShadow: '0 2px 8px rgba(22,163,74,0.3)',
  },
  rejectBtn: {
    padding: '6px 18px', borderRadius: '7px', fontSize: '0.8rem', fontWeight: 700,
    background: 'linear-gradient(135deg, #dc2626, #ef4444)', border: 'none',
    color: '#fff', cursor: 'pointer', boxShadow: '0 2px 8px rgba(220,38,38,0.3)',
  },
  approvedBadge: {
    padding: '3px 10px', borderRadius: '20px', fontSize: '0.75rem', fontWeight: 600,
    background: '#dcfce7', color: '#166534', border: '1px solid #bbf7d0',
  },
  rejectedBadge: {
    padding: '3px 10px', borderRadius: '20px', fontSize: '0.75rem', fontWeight: 600,
    background: '#fef2f2', color: '#dc2626', border: '1px solid #fecaca',
  },
  rejectedStrip: {
    background: '#fef2f2', borderBottom: '1px solid #fecaca',
    padding: '8px 20px', fontSize: '0.8rem', fontWeight: 600, color: '#dc2626',
  },
}
