import React, { useState, useEffect, useRef, useCallback } from 'react'
import DashboardLayout from '../components/DashboardLayout'
import { useAuth } from '../context/AuthContext'
import { agentAPI, filesAPI } from '../api/client'

const BROWSERS = ['Chromium', 'Firefox', 'WebKit', 'Chrome', 'Edge', 'Safari']

function downloadAsPDF(content) {
  const sanitized = content
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/\n/g, '<br/>')

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/>
  <title>Test Execution Report</title>
  <style>
    @page{margin:2cm}
    body{font-family:'Segoe UI',Arial,sans-serif;font-size:13px;line-height:1.8;color:#1f2937}
    h1{font-size:20px;color:#dc2626;border-bottom:2px solid #f87171;padding-bottom:8px;margin-bottom:16px}
    .meta{font-size:11px;color:#6b7280;margin-bottom:24px}
    .content{white-space:pre-wrap}
    .footer{margin-top:40px;font-size:10px;color:#9ca3af;border-top:1px solid #e5e7eb;padding-top:8px}
  </style></head><body>
  <h1>🚀 Test Execution Report</h1>
  <div class="meta">Generated on ${new Date().toLocaleString()} · NatWest Automator</div>
  <div class="content">${sanitized}</div>
  <div class="footer">Confidential · NatWest Automator AI Platform</div>
  </body></html>`

  const iframe = document.createElement('iframe')
  iframe.style.cssText = 'position:fixed;top:-9999px;left:-9999px;width:0;height:0;border:none'
  document.body.appendChild(iframe)
  iframe.contentDocument.open()
  iframe.contentDocument.write(html)
  iframe.contentDocument.close()
  setTimeout(() => {
    iframe.contentWindow.focus()
    iframe.contentWindow.print()
    setTimeout(() => document.body.removeChild(iframe), 1000)
  }, 300)
}

export default function ExecutionPage() {
  const { hasPermission } = useAuth()

  const [browser, setBrowser] = useState('Chromium')

  const [outputFiles, setOutputFiles] = useState([])
  const [selectedFile, setSelectedFile] = useState(null)
  const [existingContent, setExistingContent] = useState('')
  const [fetchingFiles, setFetchingFiles] = useState(false)

  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)
  const [error, setError] = useState('')
  const resultRef = useRef()

  if (!hasPermission('execution')) {
    return (
      <DashboardLayout title="Execution">
        <div style={s.denied}>
          <div style={{ fontSize: '3rem' }}>🔒</div>
          <h3 style={s.deniedTitle}>Access Restricted</h3>
          <p style={s.deniedSub}>Your role does not have permission to access this agent.</p>
        </div>
      </DashboardLayout>
    )
  }

  const fetchOutputFiles = useCallback(async () => {
    setFetchingFiles(true)
    try {
      const data = await filesAPI.listOutput('automation')
      setOutputFiles(data.files || [])
    } catch {
      setOutputFiles([])
    } finally {
      setFetchingFiles(false)
    }
  }, [])

  useEffect(() => {
    fetchOutputFiles()
  }, [fetchOutputFiles])

  const selectExistingFile = async (fname) => {
    setSelectedFile(fname)
    setExistingContent('')
    setResult(null)
    setError('')
    try {
      const text = await filesAPI.readOutput(`automation/${fname}`)
      setExistingContent(text)
    } catch {
      setError('Failed to load automation script file.')
    }
  }

  const buildTask = () => {
    return `Browser: ${browser}\n\n${existingContent}`
  }

  const handleExecute = async () => {
    const task = buildTask()
    if (!task.trim()) return
    setLoading(true)
    setError('')
    setResult(null)
    try {
      const data = await agentAPI.run('execution', task, null, 'ollama')
      setResult(data.result)
      filesAPI.saveOutput('execution', data.result).catch(() => {})
      setTimeout(() => resultRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 100)
    } catch (err) {
      setError(err.response?.data?.detail || 'Execution failed. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <DashboardLayout title="Execution">
      <div style={s.page}>

        <div>
          <h2 style={s.pageTitle}>Test Execution</h2>
          <p style={s.pageSubtitle}>
            Execute test scripts, analyze results, and generate detailed test reports.
          </p>
        </div>

        <div style={s.card}>
          <div style={s.cardBody}>

            {/* Browser selector */}
            <div style={s.configRow}>
              <div style={s.configField}>
                <label style={s.configLabel}>Browser</label>
                <select style={s.select} value={browser} onChange={e => setBrowser(e.target.value)}>
                  {BROWSERS.map(b => <option key={b} value={b}>{b}</option>)}
                </select>
              </div>
            </div>

            {/* Test Cases */}
            <p style={s.sectionTitle}>Test Cases</p>
            <p style={s.hint}>Select a test script previously generated by the Automation agent.</p>

            {fetchingFiles ? (
              <div style={s.loadingBox}>⟳ Loading test scripts...</div>
            ) : outputFiles.length === 0 ? (
              <div style={s.emptyBox}>
                <div style={{ fontSize: '1.5rem', marginBottom: '6px' }}>💭</div>
                <p>No automation scripts found.</p>
                <p style={{ fontSize: '0.8rem', color: '#9ca3af' }}>
                  Go to <strong>Automation</strong> page to generate one first.
                </p>
              </div>
            ) : (
              <div style={s.fileList}>
                {outputFiles.map(f => (
                  <div
                    key={f.name}
                    style={{
                      ...s.fileListItem,
                      borderColor: selectedFile === f.name ? '#dc2626' : '#e5e7eb',
                      background: selectedFile === f.name ? 'rgba(220,38,38,0.05)' : '#fff',
                    }}
                    onClick={() => selectExistingFile(f.name)}
                  >
                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px', flex: 1, minWidth: 0 }}>
                      <span>📄</span>
                      <div style={{ minWidth: 0 }}>
                        <div style={s.fileListItemName}>{f.name}</div>
                        <div style={s.fileListItemMeta}>
                          {(f.size / 1024).toFixed(1)} KB · {new Date(f.modified).toLocaleString()}
                        </div>
                      </div>
                    </div>
                    {selectedFile === f.name && (
                      <span style={s.selectedBadge}>✓ Selected</span>
                    )}
                  </div>
                ))}
              </div>
            )}

            {existingContent && (
              <div style={s.preview}>
                <div style={s.previewHead}>
                  <span style={{ fontWeight: 600, fontSize: '0.78rem', color: '#374151' }}>📋 Script Editor</span>
                  <span style={{ fontSize: '0.74rem', color: '#9ca3af' }}>{existingContent.length.toLocaleString()} chars</span>
                </div>
                <textarea
                  style={s.codeEditor}
                  value={existingContent}
                  onChange={e => setExistingContent(e.target.value)}
                />
              </div>
            )}

            {error && <div style={s.errorBox}>⚠️ {error}</div>}

            <button
              style={{
                ...s.actionBtn,
                opacity: loading || !existingContent.trim() ? 0.55 : 1,
                cursor:  loading || !existingContent.trim() ? 'not-allowed' : 'pointer',
              }}
              onClick={handleExecute}
              disabled={loading || !existingContent.trim()}
            >
              {loading
                ? <><span style={s.spin}>⟳</span> Executing tests...</>
                : '🚀  Execute Tests'
              }
            </button>
          </div>
        </div>

        {result && (
          <div ref={resultRef} style={s.resultCard}>
            <div style={s.resultHead}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <span style={{ fontSize: '1rem' }}>✅</span>
                <span style={s.resultTitle}>Execution Complete</span>
              </div>
              <div style={{ display: 'flex', gap: '8px' }}>
                <button style={s.copyBtn} onClick={() => navigator.clipboard.writeText(result)}>
                  📋 Copy
                </button>
                <button style={s.pdfBtn} onClick={() => downloadAsPDF(result)}>
                  ⬇️ Download PDF
                </button>
              </div>
            </div>
            <pre style={s.resultText}>{result}</pre>
            <div style={s.resultFoot}>
              💡 In the print dialog, choose <strong>Save as PDF</strong> to download.
            </div>
          </div>
        )}

      </div>
    </DashboardLayout>
  )
}

const s = {
  page:         { display: 'flex', flexDirection: 'column', gap: '20px' },
  pageTitle:    { fontSize: '1.45rem', fontWeight: 800, color: '#1f2937', marginBottom: '4px' },
  pageSubtitle: { fontSize: '0.85rem', color: '#6b7280' },
  card:         { background: '#fff', borderRadius: '14px', border: '1px solid #e5e7eb', boxShadow: '0 1px 6px rgba(0,0,0,0.05)', overflow: 'hidden' },
  cardBody:     { padding: '22px 24px', display: 'flex', flexDirection: 'column', gap: '14px' },
  configRow:    { display: 'flex', gap: '14px', flexWrap: 'wrap' },
  configField:  { display: 'flex', flexDirection: 'column', gap: '5px', flex: 1, minWidth: '140px' },
  configLabel:  { fontSize: '0.8rem', fontWeight: 600, color: '#374151' },
  select: {
    padding: '9px 12px', borderRadius: '8px', border: '1px solid #d1d5db',
    background: '#fff', fontSize: '0.875rem', color: '#374151',
    fontFamily: 'inherit', outline: 'none', cursor: 'pointer',
  },
  sectionTitle: { fontSize: '0.85rem', fontWeight: 600, color: '#374151', marginBottom: '2px' },
  hint:         { fontSize: '0.82rem', color: '#6b7280', marginBottom: '4px' },
  fileList:     { display: 'flex', flexDirection: 'column', gap: '6px', maxHeight: '260px', overflowY: 'auto' },
  fileListItem: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '10px 14px', borderRadius: '8px', border: '1px solid',
    cursor: 'pointer', gap: '10px', transition: 'all 0.15s',
  },
  fileListItemName: {
    fontSize: '0.82rem', fontWeight: 600, color: '#1f2937',
    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
  },
  fileListItemMeta: { fontSize: '0.72rem', color: '#9ca3af', marginTop: '2px' },
  selectedBadge: {
    padding: '2px 8px', borderRadius: '5px', fontSize: '0.72rem', fontWeight: 700,
    background: 'rgba(220,38,38,0.1)', color: '#dc2626', border: '1px solid rgba(220,38,38,0.2)',
    flexShrink: 0,
  },
  loadingBox: {
    padding: '20px', textAlign: 'center', color: '#dc2626',
    fontSize: '0.88rem', fontWeight: 600,
  },
  emptyBox: {
    padding: '24px', textAlign: 'center', color: '#6b7280',
    background: '#f9fafb', borderRadius: '8px', fontSize: '0.85rem',
  },
  preview:     { border: '1px solid #e5e7eb', borderRadius: '8px', overflow: 'hidden' },
  previewHead: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '7px 12px', borderBottom: '1px solid #e5e7eb', background: '#f9fafb',
  },
  codeEditor: {
    width: '100%', minHeight: '300px', padding: '12px 14px', borderRadius: '0',
    border: 'none', background: '#f8fafc', fontSize: '0.875rem',
    fontFamily: 'monospace', lineHeight: 1.65, color: '#1f2937',
    resize: 'vertical', outline: 'none', boxSizing: 'border-box',
  },
  errorBox: {
    background: 'rgba(239,68,68,0.06)', border: '1px solid rgba(239,68,68,0.2)',
    color: '#dc2626', borderRadius: '8px', padding: '10px 14px', fontSize: '0.875rem',
  },
  actionBtn: {
    padding: '12px 24px', borderRadius: '10px', fontWeight: 700, fontSize: '0.95rem',
    border: 'none', background: 'linear-gradient(135deg, #dc2626, #ef4444)',
    color: '#fff', display: 'inline-flex', alignItems: 'center', gap: '8px',
    boxShadow: '0 3px 12px rgba(220,38,38,0.28)', transition: 'opacity 0.2s', alignSelf: 'flex-start',
  },
  spin: { display: 'inline-block', animation: 'spin 1s linear infinite', fontSize: '1rem' },
  resultCard: {
    background: '#fff', borderRadius: '14px',
    border: '1.5px solid #fca5a5', boxShadow: '0 2px 14px rgba(220,38,38,0.09)', overflow: 'hidden',
  },
  resultHead: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '12px 18px', borderBottom: '1px solid #fee2e2',
    background: 'rgba(220,38,38,0.04)', flexWrap: 'wrap', gap: '10px',
  },
  resultTitle: { fontSize: '0.9rem', fontWeight: 700, color: '#991b1b' },
  copyBtn: {
    padding: '6px 14px', borderRadius: '7px', fontSize: '0.8rem', fontWeight: 600,
    background: 'rgba(220,38,38,0.08)', border: '1px solid rgba(220,38,38,0.2)',
    color: '#dc2626', cursor: 'pointer',
  },
  pdfBtn: {
    padding: '6px 16px', borderRadius: '7px', fontSize: '0.8rem', fontWeight: 700,
    background: 'linear-gradient(135deg, #dc2626, #ef4444)', border: 'none',
    color: '#fff', cursor: 'pointer', boxShadow: '0 2px 8px rgba(220,38,38,0.22)',
  },
  resultText: {
    padding: '18px 20px', fontSize: '0.875rem', lineHeight: 1.8,
    whiteSpace: 'pre-wrap', wordBreak: 'break-word', color: '#1f2937',
    fontFamily: 'inherit', maxHeight: '500px', overflowY: 'auto', margin: 0,
  },
  resultFoot: {
    padding: '9px 18px', borderTop: '1px solid #f3f4f6',
    background: '#fef2f2', fontSize: '0.75rem', color: '#dc2626',
  },
  denied:      { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '60vh', textAlign: 'center', gap: '10px' },
  deniedTitle: { fontSize: '1.3rem', fontWeight: 700, color: '#991b1b' },
  deniedSub:   { color: '#6b7280', fontSize: '0.9rem', maxWidth: '340px' },
}
